/*
 * This source file was generated by the Gradle 'init' task
 */
package company.vk.edu.distrib.compute.expanse.hw6;


import company.vk.edu.distrib.compute.expanse.hw6.node.DistributedConsensusNode;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;

public class DistributedConsensusApp {
    private DistributedConsensusApp() {}

    private static final String EXIT = "exit";
    private static final String NODE_DOES_NOT_EXIST = "Node with such id doesn't exist.";

    static void main() {
        DistributedConsensusNode.disableLogging();

        try (BufferedReader br = new BufferedReader(new InputStreamReader(System.in))) {
            System.out.println("Print the number of nodes to create. Number should be greater than 0.");
            String line = br.readLine().strip();

            Integer nodesCount = null;
            while (nodesCount == null) {
                if (EXIT.equals(line)) {
                    return;
                }
                nodesCount = tryParseInt(line);

                if (nodesCount != null && nodesCount <= 0) {
                    System.out.println("Node count should be greater than 0. Try again or type exit to quit.");
                    nodesCount = null;
                }
            }
            TreeMap<Long, DistributedConsensusNode> nodesMap = new TreeMap<>();
            for (int i = 0; i < nodesCount; i++) {
                new DistributedConsensusNode(
                        2000,
                        4000,
                        nodesMap,
                        10,
                        5000
                );
            }
            System.out.println("Starting nodes...");
            nodesMap.values().forEach(DistributedConsensusNode::start);

            while (true) {
                System.out.println("""
                        Commands available:
                        1 - print nodes state
                        2 - pause node
                        3 - resume node
                        4 - shutdown node
                        5 - start new node
                        6 - print logs
                        exit - finish program
                        """);
                System.out.println("Print command to continue: ");

                line = br.readLine().strip();

                switch (line) {
                    case "1" -> {
                        System.out.println("Press enter to stop nodes state printing.");

                        while (!br.ready()) {
                            StringBuilder sb = new StringBuilder("Nodes states: ");
                            for (DistributedConsensusNode node : nodesMap.values()) {
                                sb.append(String.format("node %d: %s, ", node.getId(), node.getState()));
                            }
                            sb.delete(sb.lastIndexOf(","), sb.length());
                            sb.append('\r');
                            System.out.print(sb);

                            Thread.sleep(100);
                        }
                    }
                    case "2" -> {
                        System.out.println("Enter node id to pause: ");
                        line = br.readLine().strip();

                        if (EXIT.equals(line)) {
                            stopNodes(nodesMap);
                            return;
                        }

                        Integer nodeId = tryParseInt(line);
                        if (!nodesMap.containsKey((long) nodeId)) {
                            System.out.println(NODE_DOES_NOT_EXIST);
                            continue;
                        }
                        if (!nodesMap.get((long) nodeId).isStarted()) {
                            System.out.println("Cannot pause node that is not started.");
                            continue;
                        }
                        nodesMap.get((long) nodeId).pause();

                    }
                    case "3" -> {
                        System.out.println("Enter node id to resume: ");
                        line = br.readLine().strip();

                        if (EXIT.equals(line)) {
                            stopNodes(nodesMap);
                            return;
                        }

                        Integer nodeId = tryParseInt(line);
                        if (!nodesMap.containsKey((long) nodeId)) {
                            System.out.println(NODE_DOES_NOT_EXIST);
                            continue;
                        }
                        if (!nodesMap.get((long) nodeId).isStarted()) {
                            System.out.println("Cannot resume node that is not started.");
                            continue;
                        }
                        nodesMap.get((long) nodeId).resume();
                    }
                    case "4" -> {
                        System.out.println("Enter node id to shutdown: ");
                        line = br.readLine().strip();

                        if (EXIT.equals(line)) {
                            stopNodes(nodesMap);
                            return;
                        }

                        Integer nodeId = tryParseInt(line);
                        if (!nodesMap.containsKey((long) nodeId)) {
                            System.out.println(NODE_DOES_NOT_EXIST);
                            continue;
                        }
                        nodesMap.get((long) nodeId).shutdown();
                        nodesMap.remove((long) nodeId);
                    }
                    case "5" -> {
                        DistributedConsensusNode node = new DistributedConsensusNode(
                                500,
                                1000,
                                nodesMap,
                                10,
                                5000
                        );
                        node.start();
                    }

                    case "6" -> {
                        System.out.println("Press enter to stop logs printing.");
                        Thread.sleep(2000);
                        DistributedConsensusNode.enableLogging(Level.INFO);
                        br.readLine();
                        DistributedConsensusNode.disableLogging();
                    }

                    case EXIT -> {
                        stopNodes(nodesMap);
                        return;
                    }

                    default -> System.out.println("Invalid command. Try again or type exit to quit.");
                }
            }

        } catch (IOException | InterruptedException e) {
            throw new RuntimeException(e);
        }

    }

    private static Integer tryParseInt(String line) {
        Integer result = null;
        try {
            result = Integer.parseInt(line);

        } catch (NumberFormatException _) {
            System.out.println("Invalid number format. Try again or type exit to quit.");
        }
        return result;
    }

    private static void stopNodes(Map<Long, DistributedConsensusNode> nodesMap) throws InterruptedException {
        nodesMap.values().forEach(DistributedConsensusNode::shutdown);
        Thread.sleep(1000);
        nodesMap.values().forEach(DistributedConsensusNode::forceShutdown);
    }
}
